"""HaluEval-QA adapter.

Each row gives a (question, right_answer, hallucinated_answer) triple, where
the hallucinated answer was generated by GPT-3.5 to look plausible. We map:

  a^+  ←  right_answer
  a^-  ←  hallucinated_answer

`expert_reliable=True` for every record — HaluEval's design assumes the
human expert always knows the right answer, so the hallucinated rep is
exactly the "model wrong, expert right" deferral target. This is what
makes `halueval_style_labels: true` (in the experiment config) flip the
y_expert label on h^- rows; see probes/training.py:prepare_training_data.
"""
from __future__ import annotations

from data.schema import Record, stable_id

DEFAULT_MAX_ROWS = 8000


def load(max_rows: int = DEFAULT_MAX_ROWS) -> list[Record]:
    from datasets import load_dataset

    ds = load_dataset("pminervini/HaluEval", "qa", split="data")
    if len(ds) > max_rows:
        ds = ds.select(range(max_rows))

    out: list[Record] = []
    for row in ds:
        q     = (row.get("question") or "").strip()
        right = (row.get("right_answer") or "").strip()
        wrong = (row.get("hallucinated_answer") or "").strip()
        if not (q and right and wrong):
            continue
        out.append(Record(
            example_id      = stable_id("halueval_qa", q),
            question        = q,
            correct_answer  = right,
            wrong_answer    = wrong,
            category        = "HaluEval-QA",
            expert_reliable = True,
        ))
    return out
