"""
Pre-extraction diagnostics for constrained-deferral LP results.

This reads per-item bootstrap diagnostics generated by:

  python scripts/constrained_deferral.py \
    --demo-bootstrap-features --model llama3_8b --dataset truthfulqa \
    --seed 0 --k-boot 20 \
    --out results/constrained_deferral_truthfulqa_bootstrap_k20.parquet

The summary parquet is useful for LP status; this script needs the companion
`*_items.parquet` file because width/AURC diagnostics are per-item quantities.
"""
from __future__ import annotations

import sys
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

_PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(_PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(_PROJECT_ROOT))

from eval.risk_coverage import aurc  # noqa: E402


K20_ITEMS = Path("results/constrained_deferral_truthfulqa_bootstrap_k20_items.parquet")
K5_ITEMS = Path("results/constrained_deferral_truthfulqa_bootstrap_k5_items.parquet")


def _require(path: Path) -> pd.DataFrame:
    if not path.exists():
        raise FileNotFoundError(
            f"Missing {path}. Re-run constrained_deferral.py with --demo-bootstrap-features "
            "and --out so the companion *_items.parquet file is written."
        )
    return pd.read_parquet(path)


def safe_logit(p: np.ndarray, eps: float = 1e-6) -> np.ndarray:
    p = np.clip(np.asarray(p, dtype=float), eps, 1.0 - eps)
    return np.log(p / (1.0 - p))


def width_distribution_stats(df: pd.DataFrame, k_label: str) -> dict[str, float]:
    pred_widths = df.p_pred_upper - df.p_pred_lower
    amb_widths = df.p_amb_upper - df.p_amb_lower

    print(f"\n=== K={k_label} width diagnostics ===")
    print(
        f"pred width: mean={pred_widths.mean():.4f}  "
        f"median={pred_widths.median():.4f}  "
        f"p90={pred_widths.quantile(0.9):.4f}  "
        f"max={pred_widths.max():.4f}"
    )
    print(
        f"amb  width: mean={amb_widths.mean():.4f}  "
        f"median={amb_widths.median():.4f}  "
        f"p90={amb_widths.quantile(0.9):.4f}  "
        f"max={amb_widths.max():.4f}"
    )

    out = {
        "k_boot": int(k_label),
        "pred_width_mean": float(pred_widths.mean()),
        "pred_width_median": float(pred_widths.median()),
        "pred_width_p90": float(pred_widths.quantile(0.9)),
        "pred_width_max": float(pred_widths.max()),
        "amb_width_mean": float(amb_widths.mean()),
        "amb_width_median": float(amb_widths.median()),
        "amb_width_p90": float(amb_widths.quantile(0.9)),
        "amb_width_max": float(amb_widths.max()),
    }

    if "y_correct" in df.columns:
        from scipy.stats import pointbiserialr

        rho_pred, p_pred = pointbiserialr(df.y_correct, pred_widths)
        rho_amb, p_amb = pointbiserialr(df.y_correct, amb_widths)
        print(f"corr(pred_width, y_correct): rho={rho_pred:+.3f} (p={p_pred:.4f})")
        print(f"corr(amb_width,  y_correct): rho={rho_amb:+.3f} (p={p_amb:.4f})")
        out.update({
            "corr_pred_width_y_correct": float(rho_pred),
            "corr_pred_width_y_correct_p": float(p_pred),
            "corr_amb_width_y_correct": float(rho_amb),
            "corr_amb_width_y_correct_p": float(p_amb),
        })
    return out


def aurc_comparison(df: pd.DataFrame) -> dict[str, float]:
    y = df.y_correct.values.astype(bool)
    gap_point = safe_logit(df.p_pred_mean) - safe_logit(df.p_amb_mean)
    gap_robust = safe_logit(df.p_pred_lower) - safe_logit(df.p_amb_lower)

    rows = {
        "point_gap": aurc(gap_point, y),
        "robust_gap": aurc(gap_robust, y),
        "lp_expected_policy": aurc(df.policy_expected.values, y),
        "raw_p_pred_mean": aurc(df.p_pred_mean.values, y),
    }
    if df.policy_robust.notna().all():
        rows["lp_robust_policy"] = aurc(df.policy_robust.values, y)

    print("\n=== AURC comparison (TruthfulQA test half) ===")
    for key, value in rows.items():
        print(f"  {key:20s} {value:.4f}")
    if "lp_robust_policy" not in rows:
        print("  lp_robust_policy   unavailable (robust LP infeasible)")
    return rows


def plot_widths(df_k20: pd.DataFrame, save_to: Path) -> None:
    fig, axes = plt.subplots(1, 2, figsize=(10, 4))
    pred_width = df_k20.p_pred_upper - df_k20.p_pred_lower
    amb_width = df_k20.p_amb_upper - df_k20.p_amb_lower

    axes[0].hist(pred_width, bins=30, alpha=0.75)
    axes[0].set_xlabel("p_pred credal width")
    axes[0].set_ylabel("count")
    axes[0].set_title(f"p_pred widths (K=20)\nmean={pred_width.mean():.3f}")

    axes[1].hist(amb_width, bins=30, alpha=0.75, color="C1")
    axes[1].set_xlabel("p_amb credal width")
    axes[1].set_ylabel("count")
    axes[1].set_title(f"p_amb widths (K=20)\nmean={amb_width.mean():.3f}")

    plt.tight_layout()
    save_to.parent.mkdir(parents=True, exist_ok=True)
    plt.savefig(save_to, dpi=150)
    print(f"\nSaved width distribution plot to {save_to}")


def main() -> None:
    df_k20 = _require(K20_ITEMS)
    df_k5 = _require(K5_ITEMS)

    rows = [
        width_distribution_stats(df_k20, "20"),
        width_distribution_stats(df_k5, "5"),
    ]
    aurc_rows = aurc_comparison(df_k20)
    for key, value in aurc_rows.items():
        rows.append({"diagnostic": key, "value": value})

    plot_widths(df_k20, Path("results/truthfulqa_credal_widths.png"))
    out = Path("results/truthfulqa_lp_diagnostics.parquet")
    pd.DataFrame(rows).to_parquet(out, index=False)
    print(f"Wrote diagnostics table to {out}")


if __name__ == "__main__":
    main()

