"""
Plot independence-panel data generated by compute_independence_panels.py.

Inputs:
  data/independence_panels/{cosines_by_cell,stc_by_cell,signal_corr_by_cell}.dat
  data/independence_panels/scatter_*.dat

Outputs:
  data/independence_panels/figures/independence_bars.{png,pdf}
  data/independence_panels/figures/scatter_*.{png,pdf}
"""
from __future__ import annotations

import argparse
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd


INPUT_DIR = Path("data/independence_panels")
OUTPUT_DIR = INPUT_DIR / "figures"
MODELS = ["LLaMA", "Mistral", "Qwen"]
MODEL_COLORS = {
    "LLaMA": "#4C78A8",
    "Mistral": "#F58518",
    "Qwen": "#54A24B",
}


def read_dat(path: Path) -> pd.DataFrame:
    return pd.read_csv(path, sep=r"\s+")


def plot_bar_panel(ax, df: pd.DataFrame, title: str, ylabel: str) -> None:
    x = np.arange(len(df))
    width = 0.24
    for i, model in enumerate(MODELS):
        offset = (i - 1) * width
        ax.bar(
            x + offset,
            df[model].astype(float),
            width=width,
            label=model,
            color=MODEL_COLORS[model],
            edgecolor="white",
            linewidth=0.6,
        )
    ax.set_title(title, fontsize=10, pad=8)
    ax.set_ylabel(ylabel)
    ax.set_xticks(x)
    ax.set_xticklabels(df["dataset"], rotation=35, ha="right")
    ax.set_ylim(0, max(0.35, np.nanmax(df[MODELS].to_numpy(dtype=float)) * 1.15))
    ax.grid(axis="y", color="#D8D8D8", linewidth=0.6, alpha=0.8)
    ax.set_axisbelow(True)
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)


def plot_independence_bars(input_dir: Path, output_dir: Path) -> None:
    cosines = read_dat(input_dir / "cosines_by_cell.dat")
    stc = read_dat(input_dir / "stc_by_cell.dat")
    signal_corr = read_dat(input_dir / "signal_corr_by_cell.dat")

    plt.rcParams.update({
        "font.size": 9,
        "axes.titlesize": 10,
        "axes.labelsize": 9,
        "legend.fontsize": 8,
    })
    fig, axes = plt.subplots(3, 1, figsize=(8.2, 8.4), constrained_layout=True)
    plot_bar_panel(
        axes[0],
        cosines,
        "Geometric Non-Independence",
        r"$|\cos(w_{pred}, w_{defer})|$",
    )
    plot_bar_panel(
        axes[1],
        stc,
        "Supervision-Target Correlation",
        r"$|\rho(y_{expert}, 1-y_{correct})|$",
    )
    plot_bar_panel(
        axes[2],
        signal_corr,
        "Signal-Output Correlation",
        r"$|\rho(p_{pred}, p_{defer})|$",
    )
    axes[0].legend(ncol=3, loc="upper right", frameon=False)
    fig.suptitle("Independence Diagnostics Across Model-Dataset Cells", fontsize=12)
    output_dir.mkdir(parents=True, exist_ok=True)
    for ext in ("png", "pdf"):
        out = output_dir / f"independence_bars.{ext}"
        fig.savefig(out, dpi=240, bbox_inches="tight")
        print(f"wrote {out}")
    plt.close(fig)


def _scatter_title(path: Path) -> str:
    stem = path.stem.removeprefix("scatter_")
    for model in ("llama3_8b", "mistral_7b", "qwen2_5_7b"):
        suffix = f"_{model}"
        if stem.endswith(suffix):
            dataset = stem[: -len(suffix)]
            model_label = {"llama3_8b": "LLaMA", "mistral_7b": "Mistral", "qwen2_5_7b": "Qwen"}[model]
            return f"{dataset} / {model_label}"
    return stem


def plot_scatter(path: Path, output_dir: Path) -> None:
    df = read_dat(path)
    colors = np.where(df["y_correct"].to_numpy(dtype=int) == 1, "#4C78A8", "#E45756")
    fig, ax = plt.subplots(figsize=(4.0, 3.6), constrained_layout=True)
    ax.scatter(
        df["p_pred"],
        df["p_defer"],
        s=7,
        c=colors,
        alpha=0.42,
        linewidths=0,
    )
    ax.set_title(_scatter_title(path), fontsize=10)
    ax.set_xlabel(r"$p_{pred}$")
    ax.set_ylabel(r"$p_{defer}$")
    ax.set_xlim(-0.02, 1.02)
    ax.set_ylim(-0.02, 1.02)
    ax.grid(color="#D8D8D8", linewidth=0.6, alpha=0.8)
    ax.set_axisbelow(True)
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)
    output_dir.mkdir(parents=True, exist_ok=True)
    for ext in ("png", "pdf"):
        out = output_dir / f"{path.stem}.{ext}"
        fig.savefig(out, dpi=240, bbox_inches="tight")
        print(f"wrote {out}")
    plt.close(fig)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input-dir", type=Path, default=INPUT_DIR)
    parser.add_argument("--output-dir", type=Path, default=OUTPUT_DIR)
    parser.add_argument(
        "--scatter",
        nargs="*",
        default=["scatter_chaosnli_llama3_8b.dat"],
        help="Scatter .dat filenames to plot. Use 'all' for every scatter file.",
    )
    args = parser.parse_args()

    plot_independence_bars(args.input_dir, args.output_dir)

    scatter_files = []
    if args.scatter == ["all"]:
        scatter_files = sorted(args.input_dir.glob("scatter_*.dat"))
    else:
        scatter_files = [args.input_dir / item for item in args.scatter]
    for path in scatter_files:
        if path.exists():
            plot_scatter(path, args.output_dir)
        else:
            print(f"WARN missing scatter file: {path}")


if __name__ == "__main__":
    main()
